master: 
  host: 10.2.0.87
  port: 3306
  username: ivenet2
  password: Business3song
  database: unpobby147_godomall_com
slave1:
  host: 10.2.0.87
  port: 3306
  username: ivenet2
  password: Business3song
  database: unpobby147_godomall_com
